name: logix_market_place
description: "logix market place app"
publish_to: 'none'
version: 1.0.11+11

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  pinput: ^5.0.0
  photo_view: ^0.15.0
  url_launcher: ^6.1.3
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  http: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  fluttertoast: ^8.2.4
  cached_network_image: ^3.4.1
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  uni_links: ^0.5.1
  share_plus: ^10.0.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true